### ISSUE TITLE
`poetry install` fails

### ISSUE THREAD

**Issue by mikkokotila** [ioxio-dataspace/example-app#13]
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/cleo/application.py", line 327, in run
    exit_code = self._run(io)
                ^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/console/application.py", line 190, in _run
    exit_code: int = super()._run(io)
                     ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/cleo/application.py", line 431, in _run
    exit_code = self._run_command(command, io)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/cleo/application.py", line 473, in _run_command
    raise error
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/cleo/application.py", line 454, in _run_command
    self._event_dispatcher.dispatch(command_event, COMMAND)
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/cleo/events/event_dispatcher.py", line 26, in dispatch
    self._do_dispatch(listeners, event_name, event)
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/cleo/events/event_dispatcher.py", line 85, in _do_dispatch
    listener(event, event_name, self)
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/console/application.py", line 283, in configure_env
    from poetry.console.commands.self.self_command import SelfCommand
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/console/commands/self/self_command.py", line 13, in <module>
    from poetry.utils.env import EnvManager
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/utils/env/__init__.py", line 9, in <module>
    from poetry.utils.env.base_env import Env
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/utils/env/base_env.py", line 15, in <module>
    from virtualenv.seed.wheels.embed import get_embed_wheel
ImportError: cannot import name 'get_embed_wheel' from 'virtualenv.seed.wheels.embed' (unknown location)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/poetry", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/console/application.py", line 411, in main
    exit_code: int = Application().run()
                     ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/cleo/application.py", line 338, in run
    self.render_error(e, io)
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/console/application.py", line 180, in render_error
    self.set_solution_provider_repository(self._get_solution_provider_repository())
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/console/application.py", line 400, in _get_solution_provider_repository
    from poetry.mixology.solutions.providers.python_requirement_solution_provider import (
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/mixology/solutions/providers/__init__.py", line 3, in <module>
    from poetry.mixology.solutions.providers.python_requirement_solution_provider import (
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/mixology/solutions/providers/python_requirement_solution_provider.py", line 9, in <module>
    from poetry.puzzle.exceptions import SolverProblemError
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/puzzle/__init__.py", line 3, in <module>
    from poetry.puzzle.solver import Solver
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/puzzle/solver.py", line 16, in <module>
    from poetry.puzzle.provider import Indicator
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/puzzle/provider.py", line 27, in <module>
    from poetry.packages.direct_origin import DirectOrigin
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/packages/direct_origin.py", line 10, in <module>
    from poetry.inspection.info import PackageInfo
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/inspection/info.py", line 24, in <module>
    from poetry.utils.env import EnvCommandError
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/utils/env/__init__.py", line 9, in <module>
    from poetry.utils.env.base_env import Env
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/utils/env/base_env.py", line 15, in <module>
    from virtualenv.seed.wheels.embed import get_embed_wheel
ImportError: cannot import name 'get_embed_wheel' from 'virtualenv.seed.wheels.embed' (unknown location)

**Comment by lietu** [comment]
I've not really looked into this at all but I'd guess this is a compatibility issue with Python 3.12 - try 3.11 if easily possible for you. It could also be as simple to fix as `poetry update` but depends on what version selectors we and all the sub-packages have happened to used, and if every dependency is updated to support it.

Python 3.12 has broken a lot of compatibility issues with various things, and the reference to `virtualenv` and `get_embed_wheel` looks similar to the other issues.

Another guess is that the Poetry version is a bit old and we've had some issues recently with 1.7.x being able to install some of the packages - might need to update to 1.8.x for either Python 3.12 or some of the more recent packages.

If the 3 options do not resolve it we can take a further look, let us know how it goes.

**Comment by lietu** [comment]
Ended up testing and on Py3.11 + Poetry 1.8.2 it just worked. Python 3.12 needed some massaging, but now both work. If you find further issues that are not covered here please reopen / file a new issue.
